#!/bin/bash


cd ../bitdust
echo
echo "##### promote changes from one repository to another"
./import ../bitdust.devel/
if [[ "$OSTYPE" == "darwin"* ]]; then
    find . -type f -name "*.py" -exec sed -i '' -e 's/_Debug = True/_Debug = False/g' {} +
else
    find . -type f -name "*.py" -exec sed -i -e 's/_Debug = True/_Debug = False/g' {} +
fi
git status

cd ..
echo
echo "##### compare repositories"
diff --brief -r bitdust/ bitdust.devel/ | grep -v ".DS_Store" | grep -v "site-packages" | grep -v ".git" | grep -v "__pycache__" | grep -v ".pyc" | grep "Only in"

cd bitdust.devel/
echo
echo "##### building history"
./history ../bitdust/
head -25 HISTORY.TXT

echo
echo "##### now you need to prepare changes in the 'public' BitDust repository:"
echo "1. cd ../bitdust/"
echo "2. use 'git add / git rm' to confirm changes"
echo "3. modify ../bitdust.devel/CHANGELOG.txt file (copy & paste console output above)"
echo "4. cd ../bitdust.devops/"
echo "5. run ./cicd/release_start"
echo
