---
- name: Run "bitdust stop"
  shell: bitdust stop
  register: out
- debug: var=out.stdout_lines

- name: Kill process if still started
  shell: kill -9 `ps -ef | grep -v grep | grep -w bitdust.py | awk '{print $2}'` | echo "process was not found"
  register: out
- debug: var=out.stdout_lines

- name: Update source code
  shell: ./up
  register: out
- debug: var=out.stdout_lines

- name: Start bitdust as daemon
  shell: bitdust daemon
  register: out
- pause:
    prompt: "Waiting for 10 seconds"
    seconds: 15
- debug: var=out.stdout_lines

- name: Run "bitdust api network_connected"
  shell: bitdust api network_connected
  register: out
- debug: var=out.stdout_lines
